#!/bin/bash

# set hostname in listener.ora
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/listener.ora

while true; do

  # TNS Listener
	tnslsnr=`ps -ef | grep tnslsnr | grep oracle`

	# PMON
	pmon=`ps -ef | egrep pmon_$ORACLE_SID'\>' | grep -v grep`

	if [ "$tnslsnr" == "" ] || [ "$pmon" == "" ]
	then
		service=oracle-${ORACLE_SID,,}
		echo `date` "starting service: " $service
		service $service start
		echo `date` "service status  : " $service
		service $service status
	fi

	sleep 1m

done;

